dataset_name: "data-inside"
paths:
  raw: "data/data-inside/raw"
  output: "data/data-inside/processed"
  in_data: "data/data-inside/raw.csv"  # Default if not using splits
  out_data: "data/data-inside/processed.csv"
models:
  yolo: "checkpoints/yolo11m-inside_fish_model.pt"
  sam: "checkpoints/sam.pth"
  depth_repo: "third_party/Depth-Anything-3"
  depth_v2_repo: "third_party/Depth-Anything-V2"
  depth_pro_repo: "third_party/ml-depth-pro"
params:
  yolo_conf: 0.8
  device: "cuda"
